### ISSUE TITLE
problematic plugins

### ISSUE THREAD

**Issue by karenetheridge** [ido50/Dist-Zilla-PluginBundle-IDOPEREL#1]
- Dist::Zilla::Plugin::VersionFromModule does not build on blead
- Dist::Zilla::Plugin::ReadmeFromPod has issues with recent dzil changes, doesn't properly handle file encodings, and will give you garbage output if you use filemungers to modify your .pm files. I recommend Dist::Zilla::Plugin::ReadmeAnyFromPod, which has none of these issues.
- you are dropping `[MetaYAML]`, which is not advised -- older toolchains may not know how to read META.json, so keeping the yaml file there is useful as a fallback mechanism
- using the config slicer and plugin remover roles makes it easy to make modifications to your configuration in a dist.ini -- see https://github.com/ido50/Plack-App-MCCS/issues/3

**Comment by ido50** [comment]
Thanks a lot for the tips, I've incorporated them in a new release. Not sure what to do about VersionFromModule though yet, I'll take care of that later.
